name: Deploy Pipeline

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------------- LOGIN GHCR ----------------
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ---------------- IMAGE NAME ----------------
      - name: Set image name
        run: echo "IMAGE=ghcr.io/kedarsuru/statuspulse" >> $GITHUB_ENV

      # ---------------- BUILD ----------------
      - name: Build image
        run: |
          docker build -t $IMAGE:${{ github.sha }} .
          docker tag $IMAGE:${{ github.sha }} $IMAGE:latest

      # ---------------- PUSH ----------------
      - name: Push image
        run: |
          docker push $IMAGE:${{ github.sha }}
          docker push $IMAGE:latest

      # ---------------- DEPLOY ----------------
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            echo "Going to app folder..."
            cd ~/statuspulse

            echo "Pulling image..."
            docker pull ghcr.io/kedarsuru/statuspulse:latest

            echo "Restarting stack..."
            docker compose down || true
            docker compose up -d

            sleep 15

            echo "Health check..."
            curl -f http://localhost:8000/health

            echo "DEPLOY SUCCESS"

      # ---------------- NOTIFY ----------------
      - name: Notify success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content":"✅ Deployment SUCCESS"}' \
          ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content":"❌ Deployment FAILED"}' \
          ${{ secrets.DISCORD_WEBHOOK }}
