name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------------- PYTHON LINT ----------------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install ruff
        run: pip install ruff

      - name: Run ruff
        run: ruff app/

      # ---------------- DOCKER LINT ----------------
      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      # ---------------- BUILD ----------------
      - name: Build image
        run: docker build -t statuspulse:test .

      # ---------------- ENV FILE ----------------
      - name: Create .env
        run: |
          echo "DB_HOST=db" >> .env
          echo "DB_NAME=postgres" >> .env
          echo "DB_USER=postgres" >> .env
          echo "DB_PASSWORD=postgres" >> .env
          echo "REDIS_HOST=redis" >> .env

      # ---------------- START ----------------
      - name: Start stack
        run: docker compose up -d

      # ---------------- WAIT ----------------
      - name: Wait for API
        run: |
          for i in {1..10}; do
            curl -f http://localhost:8000/health && break
            sleep 5
          done

      # ---------------- TEST ----------------
      - name: Run tests
        run: |
          chmod +x tests/test_integration.sh
          bash tests/test_integration.sh | tee test_output.txt

      # ---------------- ARTIFACT ----------------
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test_output.txt

      # ---------------- CLEANUP ----------------
      - name: Shutdown
        if: always()
        run: docker compose down -v
